version: '3'
services:
  server:
    build: ./server
    restart: always
    volumes:
      - ./server:/var/www/html
    ports:
      - "8080:80"
  db:
    image: mariadb:latest 
    restart: always 
    environment: 
      MARIADB_ROOT_PASSWORD: root 
    volumes: 
      - ./sql:/docker-entrypoint-initdb.d
  